### ISSUE TITLE
Grid System Issue

### ISSUE THREAD

**Issue by alexisreina** [lumapps/lumX#105]
There's a problem with the css of the grid system because of the `:last-child` pseudoelement does not work when there's more columns. Say for example you want to place 9 card elements using the class `grid__col4`. Then the right margin will be removed only in the 9th element, causing the the cards to pile in twos instead of threes and breaking the layout in big screens. A quick and dirty solution will be to use `grid__col4:nth-child(3n) { margin-right: 0 }`, but this approach has its flaws. I would reconsider using the negative `margin-left` in the `.grid` class that combined with a positive `padding-left` in the `.grid-coln` will make unnecessary the use of pseudoelements, but in order to work you need to move the current attributes of the `.grid` class to a `.container` class.

```css
  .container {
      max-width: 68em;
      margin-left: auto;
      margin-right: auto;
  }
  .grid {
      width: 100%; 
      margin-left: -24px;
      ...
  }
  .grid__col {
      width: N%;
      padding-left: 24px
      ...
  }
```

Also I've noticed the `margin-bottom`used in the `.grid__coln` doesn't work at all, I guess that's because you're floating the elements. So I'd suggest changing the grid system to the inline-block approach or to the more modern flex-box one.

P.D.: I really like your work, guys :+1: and sorry if there're any errors, english is not my mother language.
