### ISSUE TITLE
Best way to change color on input field labels e.g. checkbox

### ISSUE THREAD

**Issue by naruraghavan** [lumapps/lumX#142]
I see the following checkbox label in lumx scss files:
```css
        &:after {
            content: $mdi-var-check-box;
            color: $teal-500;
        }
```
What is the best way to override them?
