### ISSUE TITLE
flex-gutter should work for non-flex elements

### ISSUE THREAD

**Issue by vipseixas** [lumapps/lumX#266]
The way flex-gutter is implemented prevents mixing flex and non-flex elements in the same container:

```css
[flex-gutter="24"] {
    @include media-query(desk) {
        margin: 0 ($base-spacing-unit * 1.5) * -1;
    }

    & > [flex-item] {
        @include media-query(portable) {
            margin-bottom: $base-spacing-unit * 3;
        }

        @include media-query(desk) {
            padding: 0 $base-spacing-unit * 1.5;
        }
    }
}
```

Sometimes is useful to mix flex and non-flex elements, so the later does not expand to available space. I had to create rules like this:

```css
@media screen and (min-width: 1024px) {
  [flex-gutter="24"] > * {
    padding: 0 12px;
  }
}
```

Shouldn't that be the default behaviour?
