### ISSUE TITLE
checkbox css issue

### ISSUE THREAD

**Issue by jmls** [lumapps/lumX#274]
I think that something is wrong with the checkbox css definitions. My checkbox has the wrong icon

![screenshot_2015-05-19_09-43-39](https://cloud.githubusercontent.com/assets/929523/7698867/9367d3fa-fe0b-11e4-981b-f606e480e2f9.png)

![image](https://cloud.githubusercontent.com/assets/929523/7698876/a3b5a2f0-fe0b-11e4-8104-3bc9c4c895de.png)

the _checkbox.scss has the following definition,

```css
&:before {
            content: '\f1d6';
        }

        &:after {
            content: '\f1d7';
            color: $teal-500;
        }
```

but the material design css has the following : note that the labels seem to match what I am seeing (bar charts and histogram)

```css
.mdi-chart-bar::before {
  content: "\f1d6";
}

.mdi-chart-histogram::before {
  content: "\f1d7";
}
```
