### ISSUE TITLE
request: lx-select choices dropdown to match width of lx-select

### ISSUE THREAD

**Issue by aotearoan** [lumapps/lumX#469]
lumX version 1.0.5

I would like to be able to style the lx-select choices to horizontally expand to match the width of the lx-select itself. This is not possible in CSS as the choices are attached directly to the body, rather than embedded within the lx-select parent DOM.

**Comment by akinjide** [comment]
lumX v1.7.23

`lx-select` choices now match the width of the lx-select itself, did this using CSS.

```css
.lx-select {
  padding: 0.4em 1.4em 0; /*or width: 80% */
}
```
